# to turn this into a conda-linux-64.lock file, run:
# conda-lock lock --mamba -f environment.yaml -p linux-64
name: L96M2lines
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - matplotlib
  - numba
  - ipywidgets
  - pytorch
  - torchvision
  - scikit-learn
  - jupyter-book
  - jupyterlab
  - pre-commit
  - ffmpeg
  - tabulate
  - pandas
  - seaborn
  - conda-lock
  - pip
